id: P006623
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD159397
  title: ལྷ་འདྲེའི་སྲེད་པས་བདག་གིར་བྱས་པའི་ལྷ་ས།
  author: ''
  volumes:
    57d25e8ec2ab4a1d95c80d2c04bc28c1:
      image_group_id: I2PD18169
      title: ''
      volume_number: 1
      total_pages: 304
      base_file: v001.txt
